"""empty message

Revision ID: 98ba143699b9
Revises: 
Create Date: 2021-11-15 20:31:23.316394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ba143699b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['Gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors_movies',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actor.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['movie_id'], ['Movie.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    op.create_table('gender_actors',
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actor.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['gender_id'], ['Gender.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('gender_id', 'actor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender_actors')
    op.drop_table('actors_movies')
    op.drop_table('Actor')
    op.drop_table('Movie')
    op.drop_table('Gender')
    # ### end Alembic commands ###
